name: Blob storage upload

on:
  workflow_dispatch: {}
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v1
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      with:
        inlineScript: |
          az storage blob upload-batch --auth-mode key --destination "$web" --source .
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az cdn endpoint purge --content-paths "/*" --profile-name "vauhtijuoksu" --name "vauhtijuoksu-config" --resource-group "MC_Vauhtijuoksu-Azure-Sponsorship_vauhtijuoksu_norwayeast"

    - name: logout
      run: |
          az logout
      if: always()
